# Generated by Django 4.1 on 2022-12-24 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время происшествия')),
                ('source', models.CharField(choices=[('СМИ', 'СМИ'), ('Доклад тер. подр.', 'Доклад тер. подр.')], max_length=20, verbose_name='Источник')),
                ('subject', models.CharField(choices=[('Объект ТЭК', 'Объект ТЭК'), ('Ведомственная охрана', 'Ведомственная охрана')], max_length=22, verbose_name='Субъект происшествия')),
                ('inc_text', models.TextField(verbose_name='Происшествие')),
                ('result', models.TextField(blank=True, verbose_name='Результат')),
                ('comment', models.TextField(blank=True, verbose_name='Примечание')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Происшествие',
                'verbose_name_plural': 'Происшествия',
            },
        ),
    ]
