# Generated by Django 3.2 on 2021-06-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0005_delete_departament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Дата и время происшествия')),
                ('source', models.IntegerField(choices=[(1, 'СМИ'), (2, 'Доклад тер. подр.')], verbose_name='Источник')),
                ('subject', models.TextField(verbose_name='Субьект происшествия')),
                ('inc_text', models.TextField(verbose_name='Происшествие')),
                ('result', models.TextField(verbose_name='Результат')),
                ('comment', models.TextField(verbose_name='Примечание')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.region')),
            ],
        ),
    ]
