<<<<<<< HEAD
# Generated by Django 4.1 on 2022-12-24 17:24
=======
# Generated by Django 3.2 on 2021-06-24 20:50
>>>>>>> parent of 8a845cf (clear migrations)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('homepage', '0001_initial'),
=======
        ('homepage', '0005_delete_departament'),
>>>>>>> parent of 8a845cf (clear migrations)
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('date_time', models.DateTimeField(verbose_name='Дата и время происшествия')),
                ('source', models.CharField(choices=[('СМИ', 'СМИ'), ('Доклад тер. подр.', 'Доклад тер. подр.')], max_length=20, verbose_name='Источник')),
                ('subject', models.CharField(choices=[('Объект ТЭК', 'Объект ТЭК'), ('Ведомственная охрана', 'Ведомственная охрана')], max_length=22, verbose_name='Субъект происшествия')),
                ('inc_text', models.TextField(verbose_name='Происшествие')),
                ('result', models.TextField(blank=True, verbose_name='Результат')),
                ('comment', models.TextField(blank=True, verbose_name='Примечание')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Происшествие',
                'verbose_name_plural': 'Происшествия',
            },
=======
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Дата и время происшествия')),
                ('source', models.IntegerField(choices=[(1, 'СМИ'), (2, 'Доклад тер. подр.')], verbose_name='Источник')),
                ('subject', models.TextField(verbose_name='Субьект происшествия')),
                ('inc_text', models.TextField(verbose_name='Происшествие')),
                ('result', models.TextField(verbose_name='Результат')),
                ('comment', models.TextField(verbose_name='Примечание')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.region')),
            ],
>>>>>>> parent of 8a845cf (clear migrations)
        ),
    ]
