# Generated by Django 3.2 on 2021-06-30 19:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vng_incidents', '0002_auto_20210630_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 19, 48, 15, 740484, tzinfo=utc), editable=False, verbose_name='Дата и время происшествия'),
        ),
    ]
