# Generated by Django 3.2 on 2021-07-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vng_incidents', '0003_alter_incident_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время происшествия'),
        ),
    ]
