# Generated by Django 3.2 on 2021-04-25 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории объекта')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название формы проверки')),
            ],
        ),
        migrations.CreateModel(
            name='Ul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название юридического лица')),
                ('place', models.CharField(max_length=100, verbose_name='Местонахождение юридического лица')),
                ('INN', models.IntegerField(verbose_name='ИНН юридического лица')),
                ('OGRN', models.IntegerField(verbose_name='ОГРН юридического лица')),
            ],
        ),
        migrations.CreateModel(
            name='Tek_Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('place', models.CharField(max_length=100, verbose_name='Местонахождение объекта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vng_stat.category')),
                ('ul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vng_stat.ul')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_latest_check', models.DateField(verbose_name='Дата окончания последней проверки')),
                ('date_next_check', models.DateField(verbose_name='Дата начала проведения следующей проверки')),
                ('duration', models.IntegerField(verbose_name='Срок проведения проверки (Рабочих дней)')),
                ('target_text', models.TextField(default='Федеральный государственный контроль (надзор) за обеспечением безопасности объектов топливно-энергетического комплекса', verbose_name='Цель проведения проверки')),
                ('target_link', models.TextField(default='п.22 ч. 1 ст. 9 Федерального закона от 3 июля 2016 г. № 226-ФЗ «О войсках национальной гвардии Российской Федерации»', verbose_name='Основание проведения проверки')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vng_stat.form')),
                ('tek_Object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vng_stat.tek_object')),
            ],
        ),
    ]
