<<<<<<< HEAD
# Generated by Django 4.1 on 2022-12-24 17:24
=======
# Generated by Django 3.2 on 2021-04-25 11:33
>>>>>>> parent of 8a845cf (clear migrations)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('homepage', '0001_initial'),
=======
>>>>>>> parent of 8a845cf (clear migrations)
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории объекта')),
            ],
<<<<<<< HEAD
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
=======
>>>>>>> parent of 8a845cf (clear migrations)
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название формы проверки')),
            ],
<<<<<<< HEAD
            options={
                'verbose_name': 'Форма проверки',
                'verbose_name_plural': 'Формы проверки',
            },
=======
>>>>>>> parent of 8a845cf (clear migrations)
        ),
        migrations.CreateModel(
            name='Ul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=1000, verbose_name='Название юридического лица')),
                ('place', models.CharField(max_length=1000, verbose_name='Местонахождение юридического лица')),
                ('INN', models.CharField(max_length=12, verbose_name='ИНН юридического лица')),
                ('OGRN', models.CharField(max_length=13, verbose_name='ОГРН юридического лица')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
            },
=======
                ('name', models.CharField(max_length=100, verbose_name='Название юридического лица')),
                ('place', models.CharField(max_length=100, verbose_name='Местонахождение юридического лица')),
                ('INN', models.IntegerField(verbose_name='ИНН юридического лица')),
                ('OGRN', models.IntegerField(verbose_name='ОГРН юридического лица')),
            ],
>>>>>>> parent of 8a845cf (clear migrations)
        ),
        migrations.CreateModel(
            name='Tek_Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=1000, verbose_name='Название объекта')),
                ('place', models.CharField(max_length=1000, verbose_name='Местонахождение объекта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vng_stat.category', verbose_name='Категория')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.region', verbose_name='Регион')),
                ('ul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vng_stat.ul', verbose_name='Юридическое лицо')),
            ],
            options={
                'verbose_name': 'Объект ТЭК',
                'verbose_name_plural': 'Объекты ТЭК',
            },
=======
                ('name', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('place', models.CharField(max_length=100, verbose_name='Местонахождение объекта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vng_stat.category')),
                ('ul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vng_stat.ul')),
            ],
>>>>>>> parent of 8a845cf (clear migrations)
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('date_latest_check', models.DateField(blank=True, null=True, verbose_name='Дата окончания последней проверки')),
=======
                ('date_latest_check', models.DateField(verbose_name='Дата окончания последней проверки')),
>>>>>>> parent of 8a845cf (clear migrations)
                ('date_next_check', models.DateField(verbose_name='Дата начала проведения следующей проверки')),
                ('duration', models.IntegerField(verbose_name='Срок проведения проверки (Рабочих дней)')),
                ('target_text', models.TextField(default='Федеральный государственный контроль (надзор) за обеспечением безопасности объектов топливно-энергетического комплекса', verbose_name='Цель проведения проверки')),
                ('target_link', models.TextField(default='п.22 ч. 1 ст. 9 Федерального закона от 3 июля 2016 г. № 226-ФЗ «О войсках национальной гвардии Российской Федерации»', verbose_name='Основание проведения проверки')),
<<<<<<< HEAD
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vng_stat.form', verbose_name='Форма проверки')),
                ('tek_Object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vng_stat.tek_object', verbose_name='Объект ТЭК')),
            ],
            options={
                'verbose_name': 'Проверка',
                'verbose_name_plural': 'Проверки',
            },
=======
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vng_stat.form')),
                ('tek_Object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vng_stat.tek_object')),
            ],
>>>>>>> parent of 8a845cf (clear migrations)
        ),
    ]
