# Generated by Django 3.2 on 2021-04-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [

        ('vng_stat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='check',
            options={'verbose_name': 'Проверка', 'verbose_name_plural': 'Проверки'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'Форма проверки', 'verbose_name_plural': 'Формы проверки'},
        ),
        migrations.AlterModelOptions(
            name='tek_object',
            options={'verbose_name': 'Объект ТЭК', 'verbose_name_plural': 'Объекты ТЭК'},
        ),
        migrations.AlterModelOptions(
            name='ul',
            options={'verbose_name': 'Юридическое лицо', 'verbose_name_plural': 'Юридические лица'},
        ),

    ]
