# Generated by Django 3.2 on 2021-04-25 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
        ('vng_stat', '0002_auto_20210425_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='tek_object',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='homepage.region'),
            preserve_default=False,
        ),
    ]
