# Generated by Django 3.2 on 2021-04-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vng_stat', '0003_tek_object_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date_latest_check',
            field=models.DateField(blank=True, verbose_name='Дата окончания последней проверки'),
        ),
    ]
