# Generated by Django 3.2 on 2021-05-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vng_stat', '0005_auto_20210501_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ul',
            name='INN',
            field=models.CharField(max_length=12, verbose_name='ИНН юридического лица'),
        ),
        migrations.AlterField(
            model_name='ul',
            name='OGRN',
            field=models.CharField(max_length=13, verbose_name='ОГРН юридического лица'),
        ),
    ]
