# Generated by Django 3.2 on 2021-06-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='Дата создания / редактирования новости')),
                ('date_start', models.DateTimeField(verbose_name='Дата с которой нужно показывать новость')),
                ('date_end', models.DateTimeField(verbose_name='Дата до которой нужно показывать новость')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Изображение')),
                ('doc', models.FileField(upload_to='', verbose_name='Файл с документом')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
