<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.1 on 2022-12-24 17:24
=======
# Generated by Django 3.2 on 2021-06-20 14:50
>>>>>>> parent of 8a845cf (clear migrations)
=======
# Generated by Django 3.2 on 2021-06-20 14:50
>>>>>>> parent of 8a845cf (clear migrations)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
<<<<<<< HEAD
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date_create', models.DateField(auto_now=True, verbose_name='Дата создания / редактирования новости')),
                ('date_start', models.DateField(verbose_name='Дата с которой нужно показывать новость')),
                ('date_end', models.DateField(verbose_name='Дата до которой нужно показывать новость')),
                ('image', models.ImageField(blank=True, upload_to='news/image/%Y/%m/%d/', verbose_name='Изображение')),
                ('doc', models.FileField(blank=True, upload_to='news/result_report/%Y/%m/%d/', verbose_name='Файл с документом')),
=======
=======
>>>>>>> parent of 8a845cf (clear migrations)
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='Дата создания / редактирования новости')),
                ('date_start', models.DateTimeField(verbose_name='Дата с которой нужно показывать новость')),
                ('date_end', models.DateTimeField(verbose_name='Дата до которой нужно показывать новость')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Изображение')),
                ('doc', models.FileField(upload_to='', verbose_name='Файл с документом')),
<<<<<<< HEAD
>>>>>>> parent of 8a845cf (clear migrations)
=======
>>>>>>> parent of 8a845cf (clear migrations)
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
