# Generated by Django 3.2 on 2021-06-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210620_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='doc',
            field=models.FileField(blank=True, upload_to='', verbose_name='Файл с документом'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/', verbose_name='Изображение'),
        ),
    ]
