# Generated by Django 3.2 on 2021-06-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210620_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='doc',
            field=models.FileField(blank=True, upload_to='news/docs/%Y/%m/%d/', verbose_name='Файл с документом'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/image/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
