<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.1 on 2022-12-24 17:24
=======
# Generated by Django 3.2 on 2021-04-25 16:52
>>>>>>> parent of 8a845cf (clear migrations)
=======
# Generated by Django 3.2 on 2021-04-25 16:52
>>>>>>> parent of 8a845cf (clear migrations)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FedRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории объекта')),
            ],
            options={
                'verbose_name': 'Федеральный округ',
                'verbose_name_plural': 'Федеральные округи',
<<<<<<< HEAD
<<<<<<< HEAD
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное название должности')),
                ('short_name', models.CharField(max_length=100, verbose_name='Сокращенное название должности')),
                ('position', models.IntegerField(verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное название звания')),
                ('short_name', models.CharField(max_length=100, verbose_name='Сокращенное название звания')),
                ('position', models.IntegerField(verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
=======
>>>>>>> parent of 8a845cf (clear migrations)
=======
>>>>>>> parent of 8a845cf (clear migrations)
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории объекта')),
<<<<<<< HEAD
<<<<<<< HEAD
                ('timezone', models.IntegerField(default=0, help_text='GMT', verbose_name='Часовой пояс региона GMT')),
                ('fedname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.fedregion', verbose_name='Округ')),
=======
                ('fedname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.fedregion')),
>>>>>>> parent of 8a845cf (clear migrations)
=======
                ('fedname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.fedregion')),
>>>>>>> parent of 8a845cf (clear migrations)
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
<<<<<<< HEAD
<<<<<<< HEAD
                'ordering': ['name'],
=======
>>>>>>> parent of 8a845cf (clear migrations)
=======
>>>>>>> parent of 8a845cf (clear migrations)
            },
        ),
    ]
