# Generated by Django 3.2 on 2021-05-16 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное название должности')),
                ('short_name', models.CharField(max_length=100, verbose_name='Сокращенное название должности')),
                ('position', models.IntegerField(verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное название звания')),
                ('short_name', models.CharField(max_length=100, verbose_name='Сокращенное название звания')),
                ('position', models.IntegerField(verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
            },
        ),
        migrations.AddField(
            model_name='region',
            name='timezone',
            field=models.IntegerField(default=0, verbose_name='Часовой пояс региона GMT'),
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Полное название звания')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес местонахождения отдела')),
                ('region', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='homepage.region')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
    ]
