# Generated by Django 3.2 on 2021-06-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20210516_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='region',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='homepage.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='region',
            name='fedname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.fedregion', verbose_name='Округ'),
        ),
    ]
