# Generated by Django 3.2 on 2021-06-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20210624_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departament',
            name='region',
        ),
    ]
