# Generated by Django 3.2 on 2021-06-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_departament_region'),
        ('phonebook', '0005_auto_20210624_2235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departament',
        ),
    ]
