# Generated by Django 3.2 on 2021-07-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_delete_departament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='timezone',
            field=models.IntegerField(default=0, help_text='GMT', verbose_name='Часовой пояс региона GMT'),
        ),
    ]
