<<<<<<< HEAD
# Generated by Django 4.1 on 2022-12-24 17:24

from django.conf import settings
=======
# Generated by Django 3.2 on 2021-05-16 12:31

>>>>>>> parent of 8a845cf (clear migrations)
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('homepage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        ('homepage', '0002_auto_20210516_1531'),
>>>>>>> parent of 8a845cf (clear migrations)
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Полное название отдела')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес местонахождения отдела')),
                ('type', models.IntegerField(choices=[(1, 'Округ'), (2, 'Отдел'), (3, 'Отделение'), (4, 'Группа')], verbose_name='Тип подразделения')),
                ('position', models.IntegerField(help_text='Чем меньше номер, тем выше в списке.', verbose_name='Порядковый номер')),
                ('count_employees', models.IntegerField(default=0, verbose_name='Количество по штату')),
                ('region', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='homepage.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
=======
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Полное название звания')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
>>>>>>> parent of 8a845cf (clear migrations)
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('sur_name', models.CharField(default='Заполнить Фамилию', max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(default='Заполнить Имя', max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('work_phone', models.CharField(blank=True, max_length=100, verbose_name='Служебный номер')),
                ('cell_phone', models.CharField(blank=True, max_length=100, verbose_name='Мобильный номер')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='E-mail @rosgvard.ru')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.IntegerField(choices=[(0, 'На службе'), (1, 'Болен'), (2, 'Коммандировка'), (3, 'Отпуск'), (4, 'Декрет'), (5, 'Учёба'), (6, 'Откоммандирован')], default=0, verbose_name='Статус')),
                ('departament', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='phonebook.departament', verbose_name='Отдел')),
                ('job', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='homepage.job', verbose_name='Должность')),
                ('rank', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='homepage.rank', verbose_name='Звание')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('sur_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('work_phone', models.CharField(blank=True, max_length=100, verbose_name='Служебный номер')),
                ('cell_phone', models.CharField(blank=True, max_length=100, verbose_name='Мобильный номер')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='E-mail @rosgvard.ru')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('departament', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='homepage.departament')),
                ('job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='homepage.job')),
                ('rank', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='homepage.rank')),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='phonebook.status')),
>>>>>>> parent of 8a845cf (clear migrations)
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
