# Generated by Django 3.2 on 2021-05-16 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0002_auto_20210516_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Полное название звания')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sur_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('work_phone', models.CharField(blank=True, max_length=100, verbose_name='Служебный номер')),
                ('cell_phone', models.CharField(blank=True, max_length=100, verbose_name='Мобильный номер')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='E-mail @rosgvard.ru')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('departament', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='homepage.departament')),
                ('job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='homepage.job')),
                ('rank', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='homepage.rank')),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='phonebook.status')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
