# Generated by Django 3.2 on 2021-06-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_auto_20210624_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('На службе', 'На службе'), ('Болен', 'Болен'), ('Коммандировка', 'Коммандировка'), ('Отпуск', 'Отпуск'), ('Декрет', 'Декрет'), ('Уволен', 'Уволен'), ('Пенсия', 'Пенсия'), ('Переведен', 'Переведен')], max_length=20, verbose_name='Статус'),
        ),
    ]
