# Generated by Django 3.2 on 2021-06-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0005_auto_20210624_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.IntegerField(choices=[(0, 'На службе'), (1, 'Болен'), (2, 'Коммандировка'), (3, 'Отпуск'), (4, 'Декрет'), (5, 'Уволен'), (6, 'Пенсия'), (7, 'Переведен')], verbose_name='Статус'),
        ),
    ]
