# Generated by Django 3.2 on 2021-06-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0007_departament_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='type',
            field=models.IntegerField(choices=[(1, 'Округ'), (2, 'Отдел')], verbose_name='Тип подразделения'),
        ),
    ]
