# Generated by Django 3.2 on 2021-06-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0008_alter_departament_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='type',
            field=models.IntegerField(choices=[(1, 'Округ'), (2, 'Отдел'), (3, 'Отделение'), (4, 'Группа')], verbose_name='Тип подразделения'),
        ),
    ]
