# Generated by Django 3.2 on 2021-07-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0009_alter_departament_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='departament',
            name='position',
            field=models.IntegerField(default=1, help_text='Чем меньше номер, тем выше в списке.', verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
    ]
