<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.1 on 2022-12-24 17:24
=======
# Generated by Django 3.2 on 2021-08-15 20:22
>>>>>>> parent of 8a845cf (clear migrations)
=======
# Generated by Django 3.2 on 2021-08-15 20:22
>>>>>>> parent of 8a845cf (clear migrations)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
<<<<<<< HEAD
        ('homepage', '0001_initial'),
=======
        ('homepage', '0006_alter_region_timezone'),
>>>>>>> parent of 8a845cf (clear migrations)
=======
        ('homepage', '0006_alter_region_timezone'),
>>>>>>> parent of 8a845cf (clear migrations)
    ]

    operations = [
        migrations.CreateModel(
            name='TekInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
<<<<<<< HEAD
                ('tek_plan_check', models.IntegerField(default=0, verbose_name='ТЭК Количество плановых проверок')),
                ('tek_out_plan_check', models.IntegerField(default=0, verbose_name='ТЭК Количество внеплановых проверок')),
                ('tek_ls', models.IntegerField(default=0, verbose_name='ТЭК Количество задействованого л\\с')),
                ('tek_high', models.IntegerField(default=0, verbose_name='Количество высоких')),
                ('tek_mid', models.IntegerField(default=0, verbose_name='Количество средних')),
                ('tek_low', models.IntegerField(default=0, verbose_name='Количество низких')),
                ('vo_plan_check', models.IntegerField(default=0, verbose_name='ТЭК Количество плановых проверок')),
                ('vo_out_plan_check', models.IntegerField(default=0, verbose_name='ТЭК Количество внеплановых проверок')),
                ('vo_ls', models.IntegerField(default=0, verbose_name='ТЭК Количество задействованого л\\с')),
                ('vo_deps_foiv', models.IntegerField(default=0, verbose_name='Подразделения охраны - ФОИВ')),
                ('vo_deps_ul', models.IntegerField(default=0, verbose_name='Подразделения охраны - организаций')),
                ('vo_deps_ul_special', models.IntegerField(default=0, verbose_name='Подразделения охраны - ЮЛ с особыми уставными задачами')),
                ('vo_pers_vo', models.IntegerField(default=0, verbose_name='Численность ВО')),
                ('vo_pers_special', models.IntegerField(default=0, verbose_name='Численность ЮЛ с особыми уставными задачами')),
                ('vo_obj_vo', models.IntegerField(default=0, verbose_name='Объектов ВО')),
                ('vo_obj_special', models.IntegerField(default=0, verbose_name='Объектов ЮЛ с особыми уставными задачами')),
                ('vo_guns_army', models.IntegerField(default=0, verbose_name='Оружия боевого')),
                ('vo_guns_work', models.IntegerField(default=0, verbose_name='Оружия служебного')),
                ('vo_guns_civil', models.IntegerField(default=0, verbose_name='Оружия гражданского')),
                ('vo_guns_study', models.IntegerField(default=0, verbose_name='Оружия учебного')),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Информация о регионе',
                'verbose_name_plural': 'Информация о регионе',
            },
=======
=======
>>>>>>> parent of 8a845cf (clear migrations)
                ('tek_high', models.IntegerField(verbose_name='Количество высоких')),
                ('tek_mid', models.IntegerField(verbose_name='Количество средних')),
                ('tek_low', models.IntegerField(verbose_name='Количество низких')),
                ('vo_deps_foiv', models.IntegerField(verbose_name='Подразделения охраны - ФОИВ')),
                ('vo_deps_ul', models.IntegerField(verbose_name='Подразделения охраны - организаций')),
                ('vo_deps_ul_special', models.IntegerField(verbose_name='Подразделения охраны - ЮЛ с особыми уставными задачами')),
                ('vo_pers_vo', models.IntegerField(verbose_name='Численность ВО')),
                ('vo_pers_special', models.IntegerField(verbose_name='Численность ЮЛ с особыми уставными задачами')),
                ('vo_obj_vo', models.IntegerField(verbose_name='Объектов ВО')),
                ('vo_obj_special', models.IntegerField(verbose_name='Объектов ЮЛ с особыми уставными задачами')),
                ('vo_guns_army', models.IntegerField(verbose_name='Оружия боевого')),
                ('vo_guns_work', models.IntegerField(verbose_name='Оружия служебного')),
                ('vo_guns_civil', models.IntegerField(verbose_name='Оружия гражданского')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.region', unique=True)),
            ],
<<<<<<< HEAD
>>>>>>> parent of 8a845cf (clear migrations)
=======
>>>>>>> parent of 8a845cf (clear migrations)
        ),
    ]
