# Generated by Django 3.2 on 2021-08-15 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0006_alter_region_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TekInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tek_high', models.IntegerField(verbose_name='Количество высоких')),
                ('tek_mid', models.IntegerField(verbose_name='Количество средних')),
                ('tek_low', models.IntegerField(verbose_name='Количество низких')),
                ('vo_deps_foiv', models.IntegerField(verbose_name='Подразделения охраны - ФОИВ')),
                ('vo_deps_ul', models.IntegerField(verbose_name='Подразделения охраны - организаций')),
                ('vo_deps_ul_special', models.IntegerField(verbose_name='Подразделения охраны - ЮЛ с особыми уставными задачами')),
                ('vo_pers_vo', models.IntegerField(verbose_name='Численность ВО')),
                ('vo_pers_special', models.IntegerField(verbose_name='Численность ЮЛ с особыми уставными задачами')),
                ('vo_obj_vo', models.IntegerField(verbose_name='Объектов ВО')),
                ('vo_obj_special', models.IntegerField(verbose_name='Объектов ЮЛ с особыми уставными задачами')),
                ('vo_guns_army', models.IntegerField(verbose_name='Оружия боевого')),
                ('vo_guns_work', models.IntegerField(verbose_name='Оружия служебного')),
                ('vo_guns_civil', models.IntegerField(verbose_name='Оружия гражданского')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.region', unique=True)),
            ],
        ),
    ]
